- name: "Load OS specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.{{ ansible_distribution_major_version }}.yml"
        - main.yml
      paths:
        - ../vars

# Installation of tor
- include: install.yml
- include: config.yml

# Perform the running of handlers now
# So we can do "Reload systemd" (and possibly queued clean-up)
# before we start using the new/changed .service file.
- meta: flush_handlers

# Make sure tor is started and enabled
- name: Enable and start tor
  service:
    name: tor
    state: started
    enabled: yes
