---

- name: "Install OpenJDK 8"
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "openjdk-8-jre"
    - "openjdk-8-jdk-headless"

# conf-ld -- loader options to be adjusted (for i386; AMD64 normalydefault)
- name: Check DEB_BUILD_ARCH value
  shell: dpkg-architecture 2>&1 | grep '^DEB_BUILD_ARCH=' | cut -d'=' -f2
  register: deb_build_arch
  changed_when: false

# Ref Doc:
- name: Check for last version of Filebot
  script: get_basename_by_url.sh '{{ glx_filebot_download_script_url }}?type=deb&arch={{ deb_build_arch.stdout }}'
  register: glx_filebot_filename
  failed_when: not glx_filebot_filename.stdout
  changed_when: False

# - debug: msg="{{ glx_filebot_filename.stdout_lines[0] }}"

- name: "Download {{ glx_filebot_filename.stdout_lines[0] }} to {{ glx_filebot_download_dir }}/"
  get_url:
    url: "{{ glx_filebot_download_script_url }}?type=deb&arch={{ deb_build_arch.stdout }}"
    dest: "{{ glx_filebot_download_dir }}/{{ glx_filebot_filename.stdout_lines[0] }}"

- name: "Install {{ glx_filebot_download_dir }}/{{ glx_filebot_filename.stdout_lines[0] }}"
  apt:
    deb: "{{ glx_filebot_download_dir }}/{{ glx_filebot_filename.stdout_lines[0] }}"