---
glx_prefix: "/var/lib/galaxie"
glx_packages_dir: "{{ glx_prefix }}/pkgs"
glx_source_dir: "/usr/src"

glx_opt_dir: "/opt"



# sox
glx_sox_force_install: false
# Original Source
# glx_sox_repository: "http://sourceforge.net/projects/sox/files/sox/14.4.2/"
glx_sox_repository: "https://raw.githubusercontent.com/Tuuux/galaxie/master/roles/openmeetings-server/files"
glx_sox_app_name: "sox-14.4.2"
glx_sox_extension: "tar.gz"
glx_sox_download_url: "{{ glx_sox_repository }}/{{ glx_sox_app_name }}.{{ glx_sox_extension }}"
glx_sox_sha256sum: "b45f598643ffbd8e363ff24d61166ccec4836fea6d3888881b8df53e3bb55f6c"
glx_sox_source_dir: "/usr/src"
glx_sox_lib_dir: "/usr/lib"
glx_sox_prefix: "/usr"
glx_sox_sysconfdir: "/etc"

# yasm
glx_yasm_package_name: "yasm"
glx_yasm_package_version: "1.3.0"
glx_yasm_orig_filename: "{{ glx_yasm_package_name }}_{{ glx_yasm_package_version }}.orig.tar.gz"
glx_yasm_debian_filename: "{{ glx_yasm_package_name }}_{{ glx_yasm_package_version }}-2.debian.tar.xz"
glx_yasm_dsc_filename: "{{ glx_yasm_package_name }}_{{ glx_yasm_package_version }}-2.dsc"

# h264
glx_x264_package_name: "x264"
glx_x264_version: "0.148.2643+git5c65704"
glx_x264_package_version: "1"
glx_x264_orig_filename: "{{ glx_x264_package_name }}_{{ glx_x264_version }}.orig.tar.gz"
glx_x264_debian_filename: "{{ glx_x264_package_name }}_{{ glx_x264_version }}-{{ glx_x264_package_version }}.debian.tar.xz"
glx_x264_dsc_filename: "{{ glx_x264_package_name }}_{{ glx_x264_version }}-{{ glx_x264_package_version }}.dsc"

# x265
glx_x265_package_name: "x265"
glx_x265_version: "1.9"
glx_x265_package_version: "3"
glx_x265_orig_filename: "{{ glx_x265_package_name }}_{{ glx_x265_version }}.orig.tar.gz"
glx_x265_debian_filename: "{{ glx_x265_package_name }}_{{ glx_x265_version }}-{{ glx_x265_package_version }}.debian.tar.xz"
glx_x265_dsc_filename: "{{ glx_x265_package_name }}_{{ glx_x265_version }}-{{ glx_x265_package_version }}.dsc"

# fdk-aac
glx_fdk_aac_package_name: "fdk-aac"
glx_fdk_aac_version: "0.1.3+20140816"
glx_fdk_aac_package_version: "2"
glx_fdk_aac_orig_filename: "{{ glx_fdk_aac_package_name }}_{{ glx_fdk_aac_version }}.orig.tar.gz"
glx_fdk_aac_debian_filename: "{{ glx_fdk_aac_package_name }}_{{ glx_fdk_aac_version }}-{{ glx_fdk_aac_package_version }}.debian.tar.xz"
glx_fdk_aac_dsc_filename: "{{ glx_fdk_aac_package_name }}_{{ glx_fdk_aac_version }}-{{ glx_fdk_aac_package_version }}.dsc"

# ffmpeg
glx_ffmpeg_force_install: true
#
glx_ffmpeg_source_dir: "/usr/src"
glx_ffmpeg_lib_dir: "/usr/lib"
glx_ffmpeg_bin_dir: "/usr/bin"
glx_ffmpeg_prefix: "/usr"