---
- name: Check for empty /etc/apt/sources.list
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    backup: yes
  changed_when: false

- name: activate debian buster main contrib non-free repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://ftp.fr.debian.org/debian/ buster main non-free contrib"
    - "deb-src http://ftp.fr.debian.org/debian/ buster main non-free contrib"
    - "deb http://security.debian.org/ buster/updates main non-free contrib"
    - "deb-src http://security.debian.org/ buster/updates main non-free contrib"
    - "deb http://ftp.fr.debian.org/debian/ buster-updates main non-free contrib"
    - "deb-src http://ftp.fr.debian.org/debian/ buster-updates main non-free contrib"

# DEBMULTIMEDIA
#- name: activate ded-multimedia key
#  apt_key:
#    keyserver="pgp.mit.edu"
#    id="5C808C2B65558117"
#    state=present
#  when: "{{ 'multimedia' in group_names }}"
#
#- name: activate debian deb-multimedia repository
#  apt_repository:
#    repo="{{ item }}"
#    state=present
#  when: "{{ 'multimedia' in group_names }}"
#  with_items:
#    - "deb http://www.deb-multimedia.org stretch main non-free"

#    - "deb-src http://www.deb-multimedia.org sid main"

- name: Cleanup apt cache
  command: apt-get clean warn=no
  changed_when: False

- name: run apt-get update
  apt:
    update_cache: yes

- name: run apt-get upgrade
  apt:
    upgrade: full
