---
# pre-require
- name: import i2p key
  apt_key:
    url: "{{ glx.i2p.apt_key_url }}"
    state: present

- name: "Download {{ glx.i2p.keyring_deb_file }} from {{ glx.i2p.repo_url }}"
  get_url:
    url: "{{ glx.i2p.repo_url }}pool/main/i/i2p-keyring/{{ glx.i2p.keyring_deb_file }}"
    dest: "/tmp/i2p-keyring_2016.10.01_all.deb"
  changed_when: False

- name: "Install {{ glx.i2p.keyring_deb_file }}"
  apt:
    deb: "/tmp/{{ glx.i2p.keyring_deb_file }}"

- name: "remove /tmp/{{ glx.i2p.keyring_deb_file }}"
  file:
    path: "/tmp/{{ glx.i2p.keyring_deb_file }}"
    state: absent
  changed_when: False

# For Stretch (not available until I2P 0.9.30):
- name: "Add i2p repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb {{ glx.i2p.repo_url }} stretch main"
    - "deb-src {{ glx.i2p.repo_url }} stretch main"
  changed_when: False

- name: "Install i2p-router"
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ glx.i2p.packages }}"


- name: "Configure I2P router to be started at boot"
  debconf:
    name: "i2p"
    question: "i2p/daemon"
    value: "{{ glx.i2p.debconf_daemon }}"
    vtype: "select"
  changed_when: "False"

- name: "Configure the the account i2psvc when running as a daemon"
  debconf:
    name: "i2p"
    question: "i2p/user"
    value: "{{ glx.i2p.debconf_user }}"
    vtype: "string"
  changed_when: "False"

- name: "Configure Memory that can be allocated to I2P"
  debconf:
    name: "i2p"
    question: "i2p/memory"
    value: "{{ glx.i2p.debconf_memory }}"
    vtype: "string"
  changed_when: "False"

- name: "Configure I2P router to use AppArmor"
  debconf:
    name: "i2p"
    question: "i2p/aa"
    value: "{{ glx.i2p.debconf_apparmor }}"
    vtype: "select"
  changed_when: "False"