### Service Systemd
### Enable services
- name: enable qmail-{{ glx_sqmail_service_delivery.name }}
  service:
    name: "qmail-send"
    state: started
    enabled: yes
  when: glx_sqmail_service_delivery.enable

- name: enable qmail-{{ glx_sqmail_service_smtp.name }}
  service:
    name: "qmail-smtpd"
    state: started
    enabled: yes
  when: glx_sqmail_service_smtp.enable

- name: enable qmail-{{ glx_sqmail_service_smtps.name }}
  service:
    name: "qmail-smtpsd"
    state: started
    enabled: yes
  when: glx_sqmail_service_smtps.enable

- name: enable qmail-{{ glx_sqmail_service_submission.name }}
  service:
    name: "qmail-smtpsub"
    state: started
    enabled: yes
  when: glx_sqmail_service_submission.enable

- name: enable qmail-{{ glx_sqmail_service_pop3.name }}
  service:
    name: "qmail-pop3d"
    state: started
    enabled: yes
  when: glx_sqmail_service_pop3.enable

- name: enable qmail-{{ glx_sqmail_service_pop3s.name }}
  service:
    name: "qmail-pop3sd"
    state: started
    enabled: yes
  when: glx_sqmail_service_pop3s.enable

- name: enable qmail-{{ glx_sqmail_service_qmqp.name }}
  service:
    name: "qmail-qmqpd"
    state: started
    enabled: yes
  when: glx_sqmail_service_qmqp.enable

- name: enable qmail-{{ glx_sqmail_service_qmtp.name }}
  service:
    name: "qmail-qmtpd"
    state: started
    enabled: yes
  when: glx_sqmail_service_qmtp.enable

- name: enable qmail-{{ glx_sqmail_service_qmtps.name }}
  service:
    name: "qmail-qmtpsd"
    state: started
    enabled: yes
  when: glx_sqmail_service_qmtps.enable

### Disable services
- name: disable qmail-{{ glx_sqmail_service_delivery.name }}
  service:
    name: "qmail-send"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_delivery.enable

- name: disable qmail-{{ glx_sqmail_service_smtp.name }}
  service:
    name: "qmail-smtpd"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_smtp.enable

- name: disable qmail-{{ glx_sqmail_service_smtps.name }}
  service:
    name: "qmail-smtpsd"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_smtps.enable

- name: disable qmail-{{ glx_sqmail_service_submission.name }}
  service:
    name: "qmail-smtpsub"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_submission.enable

- name: disable qmail-{{ glx_sqmail_service_pop3.name }}
  service:
    name: "qmail-pop3d"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_pop3.enable

- name: disable qmail-{{ glx_sqmail_service_pop3s.name }}
  service:
    name: "qmail-pop3sd"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_pop3s.enable

- name: disable qmail-{{ glx_sqmail_service_qmqp.name }}
  service:
    name: "qmail-qmqpd"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_qmqp.enable

- name: disable qmail-{{ glx_sqmail_service_qmtp.name }}
  service:
    name: "qmail-qmtpd"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_qmtp.enable

- name: disable qmail-{{ glx_sqmail_service_qmtps.name }}
  service:
    name: "qmail-qmtpsd"
    state: stopped
    enabled: no
  when: not glx_sqmail_service_qmtps.enable
