---
- include: Debian/8/main.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8" or ansible_lsb.codename == "jessie"

- include: Debian/9/main.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9" or ansible_lsb.codename == "stretch"
