---
- name: Check directorys
  file:
    path="{{item}}"
    owner=root
    group=root
    state=directory
    mode=0755
  with_items:
    - "{{ glx_packages_dir }}"
    - "{{ glx_opt_dir }}"
    - "{{ glx_src_dir }}"

- include: config-apt.yml
  tags: config, config-apt

- include: install-java.yml
  tags: install, install-java

- include: install-packages.yml
  tags: install, install-packages

- include: build-yasm.yml
  tags: install, install-yasm, build-yasm

- include: build-x264.yml
  tags: install, install-x264, build-x264

- include: build-x265.yml
  tags: install, install-x265, build-x265

- include: build-fdk-aac.yml
  tags: install, install-fdk-aac, build-fdk-aac

- include: build-libmp3lame.yml
  tags: install, install-libmp3lame, build-libmp3lame

- include: build-opus.yml
  tags: install, install-libopus, build-libopus

- include: build-sox.yml
  tags: install, install-sox, build-sox

- include: build-ffmpeg.yml
  tags: install, install-ffmpeg, build-ffmpeg